### ISSUE TITLE
kicode moje prdel

### ISSUE THREAD

**Issue by hans1024** [martinrotter/kistyles#3]
Jsem z nakeho nepochopitelneho duvodu nuceny pouzivat tenhle styl, asi nejaka akademicka onanie. Ale ktery magor vymyslel nastaveni tabsize=2 a flexiblecolumns=true to fakt nepochopim. Rozbite vsechny zdrojaky. A samozrejme, ze moje nastaveni to ignoruje, takze musim editovat puvodni idiotsky styl WTF? Kdo sakra si, abys mi kecal do coding stylu?!?

**Comment by martinrotter** [comment]
Atributy zobrazení zdrojových kódů jsem volil podle svého uvážení a dosud nikdo nenavrhnul jejich změnu.

Takže, když použiju Váš jazyk (nevím, jakým právem mi tykáte), tak ten "magor" jsem byl já. Ten idiotský styl jsem také napsal já. A ten, kdo Vám kecá do "coding stylu" jsem (hádáte správně) také já.

Dovolte mi, abych navázal. Až se se rozhodnete místo stupidních kidů postnout pull request nebo patch, tak neváhejte, ale toto vylévání srdíčka musím zavřít.
