### ISSUE TITLE
Zalamování url v bibliografii

### ISSUE THREAD

**Issue by novalu** [martinrotter/kistyles#5]
Odkazy v BibTeX bibliografii se mi nezalamovaly a žádné nalezené metody nepomáhaly. Pomohlo až zakomentování

`\renewcommand{\url}[1]{\orghref{#1}{#1}}`
v kibase.sty

Nakolik je to feature nebo bug nedokáži posoudit. Zkoušel jsem moji bibliografii i v guide.tex abych vyloučil problémové balíčky nebo nějaké jiné úpravy ale odkazy přetékaly i tam.

![overflow](https://cloud.githubusercontent.com/assets/6546116/9140697/62d298b2-3d33-11e5-9aa4-946b60f2bb31.png)

Nedopatřením se commit, který řádek komentuje dostal do pull requestu, který řeší typo v „Bibliographic data“

Problémová bibliografie je k dispozici zde: http://www.novaklukas.cz/files/bibliografie.bib

**Comment by martinrotter** [comment]
S tím makrem \url jsem tam skutečně bojoval. Pokud se zdálo, že zakomentování to fixuje a nikde jinde to nehapruje, tak je to OK. Vím, že s makrem \url a s bibliografiema jsem měl problém, který ten řádek jaksi řešil, ale zkusme to.
