### ISSUE TITLE
Přijimení autorů v bibliografii

### ISSUE THREAD

**Issue by novalu** [martinrotter/kistyles#6]
V aktuálním stylu jsou přijimení autorů v bibliografii provedena kapitálkami. To jsem v žádném článku, na který jsem narazil neviděl. Navíc to nevypadá moc dobře. Nebo je to nějaká česká specialita?

FYI: Oprava se nedopatřením dostala do pull requestu opravující bibliografii.

**Comment by martinrotter** [comment]
Vypadá ok, dobře.
